unit Infra.ORM.Tests.Integracao.Firebird;

{
  Responsabilidade:
    Suite de testes de integração contra banco Firebird real.
    Requer banco configurado nas constantes abaixo.
    Execute separadamente dos testes unitários.
}

interface

uses
  DUnitX.TestFramework,
  System.SysUtils,
  System.Generics.Collections,
  System.Rtti,
  Infra.ORM.Core.Common.Tipos,
  Infra.ORM.Core.Contracts,
  Infra.ORM.Core.Exceptions,
  Infra.ORM.FireDAC.Configuracao,
  Infra.ORM.Firebird.Dialeto,
  Infra.ORM.Tests.Integracao.Base;

const
  // Ajuste para seu ambiente de teste
  FB_SERVIDOR    = 'localhost';
  FB_BANCO       = 'C:\Temp\orm_test.fdb';
  FB_USUARIO     = 'SYSDBA';
  FB_SENHA       = 'masterkey';
  FB_CHARSET     = 'UTF8';

type

  [TestFixture]
  TTestesIntegracaoFirebird = class(TFixtureIntegracaoBase)
  strict protected
    function CriarConfiguracao: TConfiguracaoConexao; override;
    function CriarDialeto: IOrmDialeto; override;
    procedure CriarEstruturaBanco; override;
    procedure RemoverEstruturaBanco; override;

  public

    // ── CRUD básico ───────────────────────────────────────────────────────

    [Test]
    procedure DeveInserirClienteComAutoIncremento;

    [Test]
    procedure DeveBuscarClientePorId;

    [Test]
    procedure DeveAtualizarCliente;

    [Test]
    procedure DeveDeletarCliente;

    [Test]
    procedure DeveListarTodosClientes;

    // ── UUID v7 ───────────────────────────────────────────────────────────

    [Test]
    procedure DeveInserirPedidoComUuidV7;

    [Test]
    procedure DeveBuscarPedidoPorUuidV7;

    // ── Transações ────────────────────────────────────────────────────────

    [Test]
    procedure DeveConfirmarTransacao;

    [Test]
    procedure DeveDesfazerTransacao;

    [Test]
    procedure DeveRollbackAutomaticoAoDestruirTransacao;

    // ── Validação ─────────────────────────────────────────────────────────

    [Test]
    procedure DeveLancarExcecaoParaCampoObrigatorioVazio;

    [Test]
    procedure DeveLancarExcecaoParaNomeMaiorQuePermitido;

    // ── Concorrência ──────────────────────────────────────────────────────

    [Test]
    procedure DeveDetectarUpdateSemLinhasAfetadas;
  end;

implementation

uses
  Infra.ORM.Core.Session.Fabrica,
  Infra.ORM.FireDAC.Fabrica;

{ TTestesIntegracaoFirebird }

function TTestesIntegracaoFirebird.CriarConfiguracao: TConfiguracaoConexao;
begin
  Result := TConfiguracaoFirebird.Criar
    .Servidor(FB_SERVIDOR)
    .BancoDados(FB_BANCO)
    .Usuario(FB_USUARIO)
    .Senha(FB_SENHA)
    .Charset(FB_CHARSET)
    .Construir;
end;

function TTestesIntegracaoFirebird.CriarDialeto: IOrmDialeto;
begin
  Result := TDialetoFirebird.Create;
end;

procedure TTestesIntegracaoFirebird.CriarEstruturaBanco;
var
  LSessaoAdmin: IOrmSessao;
  LComando: IOrmComando;
  LSQL: string;
begin
  LSessaoAdmin := FFabricaSessao.CriarSessao;

  // Criar tabela de clientes de teste
  LSQL :=
    'RECREATE TABLE ORM_TEST_CLIENTES (' +
    '  ID        INTEGER   NOT NULL GENERATED BY DEFAULT AS IDENTITY,' +
    '  NOME      VARCHAR(150) NOT NULL,' +
    '  EMAIL     VARCHAR(200),' +
    '  CRIADO_EM TIMESTAMP,' +
    '  CONSTRAINT PK_ORM_TEST_CLI PRIMARY KEY (ID)' +
    ')';

  LComando := LSessaoAdmin.ObterConexao.CriarComando;
  LComando.DefinirSQL(LSQL);
  try
    LComando.ExecutarSemRetorno;
  except
    // Ignora se já existir
  end;

  // Criar tabela de pedidos de teste
  LSQL :=
    'RECREATE TABLE ORM_TEST_PEDIDOS (' +
    '  ID         VARCHAR(36)   NOT NULL,' +
    '  CLIENTE_ID INTEGER       NOT NULL,' +
    '  TOTAL      NUMERIC(18,2) NOT NULL DEFAULT 0,' +
    '  CONSTRAINT PK_ORM_TEST_PED PRIMARY KEY (ID)' +
    ')';

  LComando := LSessaoAdmin.ObterConexao.CriarComando;
  LComando.DefinirSQL(LSQL);
  try
    LComando.ExecutarSemRetorno;
  except
    // Ignora se já existir
  end;
end;

procedure TTestesIntegracaoFirebird.RemoverEstruturaBanco;
var
  LSessaoAdmin: IOrmSessao;
  LComando: IOrmComando;
begin
  LSessaoAdmin := FFabricaSessao.CriarSessao;

  for var LSQL in [
    'DELETE FROM ORM_TEST_PEDIDOS',
    'DELETE FROM ORM_TEST_CLIENTES'] do
  begin
    LComando := LSessaoAdmin.ObterConexao.CriarComando;
    LComando.DefinirSQL(LSQL);
    try
      LComando.ExecutarSemRetorno;
    except
      // Ignora erros de limpeza
    end;
  end;
end;

procedure TTestesIntegracaoFirebird.DeveInserirClienteComAutoIncremento;
var
  LCliente: TClienteIntegracao;
  LTransacao: IOrmTransacao;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Rodrigo Teste';
  LCliente.Email := 'rodrigo@teste.com';

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LCliente);
    LTransacao.Commit;

    Assert.IsTrue(LCliente.Id > 0,
      'ID deve ser preenchido após INSERT com autoincremento');
    Assert.IsTrue(LCliente.CriadoEm > 0,
      'CriadoEm deve ser preenchido automaticamente');
  except
    LTransacao.Rollback;
    raise;
  end;
end;

procedure TTestesIntegracaoFirebird.DeveBuscarClientePorId;
var
  LCliente: TClienteIntegracao;
  LBuscado: TClienteIntegracao;
  LTransacao: IOrmTransacao;
  LId: Int64;
begin
  // Inserir
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Busca Teste';
  LCliente.Email := 'busca@teste.com';

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LCliente);
    LId := LCliente.Id;
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  // Buscar em nova sessão
  LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
    TValue.From<Int64>(LId));

  Assert.IsNotNull(LBuscado,
    'Deve encontrar o cliente inserido');
  Assert.AreEqual('Busca Teste', LBuscado.Nome);
  Assert.AreEqual(LId, LBuscado.Id);
end;

procedure TTestesIntegracaoFirebird.DeveAtualizarCliente;
var
  LCliente: TClienteIntegracao;
  LBuscado: TClienteIntegracao;
  LTransacao: IOrmTransacao;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Nome Original';

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LCliente);
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LCliente.Nome := 'Nome Atualizado';

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Atualizar(LCliente);
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
    TValue.From<Int64>(LCliente.Id));

  Assert.AreEqual('Nome Atualizado', LBuscado.Nome,
    'Nome deve estar atualizado no banco');
end;

procedure TTestesIntegracaoFirebird.DeveDeletarCliente;
var
  LCliente: TClienteIntegracao;
  LBuscado: TClienteIntegracao;
  LTransacao: IOrmTransacao;
  LId: Int64;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Para Deletar';

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LCliente);
    LId := LCliente.Id;
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Deletar(LCliente);
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
    TValue.From<Int64>(LId));

  Assert.IsNull(LBuscado,
    'Cliente deletado não deve ser encontrado');
end;

procedure TTestesIntegracaoFirebird.DeveListarTodosClientes;
var
  LClientes: TObjectList<TClienteIntegracao>;
  LTransacao: IOrmTransacao;
  LNomesEsperados: TArray<string>;
  LIndice: Integer;
begin
  // Limpar e inserir conjunto conhecido
  RemoverEstruturaBanco;

  LNomesEsperados := ['Alpha', 'Beta', 'Gamma'];

  LTransacao := FSessao.IniciarTransacao;
  try
    for LIndice := 0 to High(LNomesEsperados) do
    begin
      var LCliente      := TClienteIntegracao.Create;
      LCliente.Nome     := LNomesEsperados[LIndice];
      FSessao.Inserir(LCliente);
    end;
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LClientes := FSessao.Listar<TClienteIntegracao>;
  try
    Assert.AreEqual(3, LClientes.Count,
      'Deve retornar exatamente 3 clientes');
  finally
    LClientes.Free;
  end;
end;

procedure TTestesIntegracaoFirebird.DeveInserirPedidoComUuidV7;
var
  LPedido: TPedidoIntegracao;
  LTransacao: IOrmTransacao;
begin
  LPedido           := TPedidoIntegracao.Create;
  LPedido.ClienteId := 1;
  LPedido.Total     := 250.99;

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LPedido);
    LTransacao.Commit;

    Assert.IsFalse(LPedido.Id.IsEmpty,
      'ID UUID v7 deve ser gerado antes do INSERT');
    Assert.AreEqual(36, Length(LPedido.Id),
      'UUID v7 deve ter 36 caracteres no formato padrão');
  except
    LTransacao.Rollback;
    raise;
  end;
end;

procedure TTestesIntegracaoFirebird.DeveBuscarPedidoPorUuidV7;
var
  LPedido: TPedidoIntegracao;
  LBuscado: TPedidoIntegracao;
  LTransacao: IOrmTransacao;
  LId: string;
begin
  LPedido           := TPedidoIntegracao.Create;
  LPedido.ClienteId := 1;
  LPedido.Total     := 150.00;

  LTransacao := FSessao.IniciarTransacao;
  try
    FSessao.Inserir(LPedido);
    LId := LPedido.Id;
    LTransacao.Commit;
  except
    LTransacao.Rollback;
    raise;
  end;

  LBuscado := FSessao.BuscarPorId<TPedidoIntegracao>(
    TValue.From<string>(LId));

  Assert.IsNotNull(LBuscado);
  Assert.AreEqual(LId, LBuscado.Id);
  Assert.AreEqual(150.00, LBuscado.Total, 0.001);
end;

procedure TTestesIntegracaoFirebird.DeveConfirmarTransacao;
var
  LCliente: TClienteIntegracao;
  LTransacao: IOrmTransacao;
  LBuscado: TClienteIntegracao;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Commit Test';

  LTransacao := FSessao.IniciarTransacao;
  FSessao.Inserir(LCliente);
  LTransacao.Commit;

  // Deve ser visível após commit
  LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
    TValue.From<Int64>(LCliente.Id));

  Assert.IsNotNull(LBuscado,
    'Registro deve ser persistido após commit');
end;

procedure TTestesIntegracaoFirebird.DeveDesfazerTransacao;
var
  LCliente: TClienteIntegracao;
  LTransacao: IOrmTransacao;
  LBuscado: TClienteIntegracao;
  LId: Int64;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Rollback Test';

  LTransacao := FSessao.IniciarTransacao;
  FSessao.Inserir(LCliente);
  LId := LCliente.Id;
  LTransacao.Rollback;

  // Não deve ser visível após rollback
  if LId > 0 then
  begin
    LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
      TValue.From<Int64>(LId));

    Assert.IsNull(LBuscado,
      'Registro NÃO deve existir após rollback');
  end;
end;

procedure TTestesIntegracaoFirebird.DeveRollbackAutomaticoAoDestruirTransacao;
var
  LCliente: TClienteIntegracao;
  LBuscado: TClienteIntegracao;
  LId: Int64;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome  := 'Auto Rollback';

  // Bloco isolado — transação destruída sem commit
  begin
    var LTransacao := FSessao.IniciarTransacao;
    FSessao.Inserir(LCliente);
    LId := LCliente.Id;
    // LTransacao destruído aqui → rollback automático
  end;

  if LId > 0 then
  begin
    LBuscado := FSessao.BuscarPorId<TClienteIntegracao>(
      TValue.From<Int64>(LId));

    Assert.IsNull(LBuscado,
      'Rollback automático deve ter impedido a persistência');
  end;
end;

procedure TTestesIntegracaoFirebird.DeveLancarExcecaoParaCampoObrigatorioVazio;
var
  LCliente: TClienteIntegracao;
begin
  LCliente      := TClienteIntegracao.Create;
  LCliente.Nome := ''; // obrigatório — deve falhar

  Assert.WillRaise(
    procedure
    begin
      var LTrans := FSessao.IniciarTransacao;
      try
        FSessao.Inserir(LCliente);
        LTrans.Commit;
      except
        LTrans.Rollback;
        raise;
      end;
    end,
    EOrmValidacaoExcecao,
    'Deve lançar EOrmValidacaoExcecao para campo obrigatório vazio');
end;

procedure TTestesIntegracaoFirebird.DeveLancarExcecaoParaNomeMaiorQuePermitido;
var
  LCliente: TClienteIntegracao;
begin
  LCliente      := TClienteIntegracao.Create;
  // 151 caracteres — limite é 150
  LCliente.Nome := StringOfChar('X', 151);

  Assert.WillRaise(
    procedure
    begin
      var LTrans := FSessao.IniciarTransacao;
      try
        FSessao.Inserir(LCliente);
        LTrans.Commit;
      except
        LTrans.Rollback;
        raise;
      end;
    end,
    EOrmValidacaoExcecao,
    'Deve lançar EOrmValidacaoExcecao para string acima do tamanho máximo');
end;

procedure TTestesIntegracaoFirebird.DeveDetectarUpdateSemLinhasAfetadas;
var
  LCliente: TClienteIntegracao;
begin
  LCliente    := TClienteIntegracao.Create;
  LCliente.Id := MaxInt64; // ID inexistente
  LCliente.Nome := 'Fantasma';

  Assert.WillRaise(
    procedure
    begin
      var LTrans := FSessao.IniciarTransacao;
      try
        FSessao.Atualizar(LCliente);
        LTrans.Commit;
      except
        LTrans.Rollback;
        raise;
      end;
    end,
    EOrmConcorrenciaExcecao,
    'Deve detectar que nenhuma linha foi afetada no UPDATE');
end;

initialization
  TDUnitX.RegisterTestFixture(TTestesIntegracaoFirebird);

end.
