{
  DDL de referência para a tabela ORM_AUDITORIA

  ── Firebird ──────────────────────────────────────────────────────────────────
}
const
  DDL_AUDITORIA_FIREBIRD =
    'CREATE TABLE ORM_AUDITORIA (' +
    '  ID             INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,' +
    '  OCORRIDO_EM    TIMESTAMP             NOT NULL,' +
    '  OPERACAO       VARCHAR(20)           NOT NULL,' +
    '  ENTIDADE       VARCHAR(150)          NOT NULL,' +
    '  CHAVE          VARCHAR(500),' +
    '  IDENTIDADE     VARCHAR(150),' +
    '  SUCESSO        CHAR(1)               NOT NULL DEFAULT ''S'',' +
    '  DURACAO_MS     INTEGER               DEFAULT 0,' +
    '  MENSAGEM_ERRO  VARCHAR(2000),' +
    '  DADOS          BLOB SUB_TYPE TEXT,' +
    '  CONSTRAINT PK_ORM_AUDITORIA PRIMARY KEY (ID)' +
    ')';

{
  ── MySQL ──────────────────────────────────────────────────────────────────
}
const
  DDL_AUDITORIA_MYSQL =
    'CREATE TABLE `ORM_AUDITORIA` (' +
    '  `ID`            BIGINT       NOT NULL AUTO_INCREMENT,' +
    '  `OCORRIDO_EM`   DATETIME(3)  NOT NULL,' +
    '  `OPERACAO`      VARCHAR(20)  NOT NULL,' +
    '  `ENTIDADE`      VARCHAR(150) NOT NULL,' +
    '  `CHAVE`         VARCHAR(500),' +
    '  `IDENTIDADE`    VARCHAR(150),' +
    '  `SUCESSO`       CHAR(1)      NOT NULL DEFAULT ''S'',' +
    '  `DURACAO_MS`    INT          DEFAULT 0,' +
    '  `MENSAGEM_ERRO` VARCHAR(2000),' +
    '  `DADOS`         LONGTEXT,' +
    '  PRIMARY KEY (`ID`),' +
    '  INDEX `IDX_AUDITORIA_ENTIDADE` (`ENTIDADE`, `OCORRIDO_EM`),' +
    '  INDEX `IDX_AUDITORIA_IDENTIDADE` (`IDENTIDADE`)' +
    ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';
